version: 4

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains airbnb listings.
    data_tests:
      - test_minimum_row_count:
          arguments:
            min_row_count: 100000
          # if we don't want the whole pipeline stop when this specific test fails
          # we can add severity: warn, then the console log will just show warning
          #severity: warn
    columns:
    - name: listing_id
      description: Primary key for listing
      data_tests:
        - unique
        - not_null
    - name: host_id
      description: Primary key for host
      data_tests:
        - not_null
        - relationships:
            arguments:
              to: ref('dim_hosts_cleansed')
              field: host_id
    - name: room_type
      description: Room type for apartment
      data_tests:
        - accepted_values:
            values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

    - name: minimum_nights
      description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
      data_tests:
      - test_positive_values
    
  - name: dim_hosts_cleansed
    description: '{{doc("dim_hosts_cleansed")}}'
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
        data_tests:
          - unique
          - not_null
      - name: host_name
        data_type: string
        data_tests:
          - not_null
      - name: is_superhost
        data_type: string
        data_tests:
          - accepted_values:
              values: ['t', 'f']
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp
  
  - name: fct_reviews
    columns:
      - name: listing_id
        data_tests:
          - not_null
      - name: review_sentiment
        data_tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings') # we could define models too by ref("other_model")
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .95
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 3000
              max_value: 8000
              severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number